# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# -----
#
# A packaged release will be uploaded for a tagged version.
#
image: python:3.8

definitions:
  caches:
    pyinstaller: build

pipelines:
  tags:
    'windows*':
      - step:
          name: Create Windows Release Archive
          caches:
            - pip
            - pyinstaller
          script:
            - apt update -qq && apt install python3-venv zip -y
            - python3 -m pip install --upgrade pip
            - python3 -m venv venv
            - source venv/bin/activate
            - pip install -r requirements.txt
            - pip install pyinstaller
            - pyinstaller main.spec
            - cd dist/uScope/
            - cp ../../README.md .
            - ARCHIVE="uScope_${BITBUCKET_TAG}.zip"
            - zip $ARCHIVE *
            - pipe: atlassian/bitbucket-upload-file:0.3.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: '*.zip'
